### ISSUE TITLE
Settings aren't persistent

### ISSUE THREAD

**Issue by OrangeNote** [ToyDragon/ROR2ModShared#2]
I don't know exactly how bepinex config files work, but apparently there's no way to have persistent settings at the moment (it doesn't remember mods and it always opens the ui at launch) . I don't know if it's an intended behavior, so I'm creating this issue. I hope it helps! :)

**Comment by ToyDragon** [comment]
Should be resolved now with commit https://github.com/ToyDragon/ROR2ModShared/commit/f44522f69b4132ca86708f196f0658684877f7d8
