### ISSUE TITLE
[FR] Support for manually adding mod update parameters.

### ISSUE THREAD

**Issue by JohnEdwa** [ToyDragon/ROR2ModShared#3]
I really like where this is going, but it's very unlikely every single mod author is going to implement this library so giving users the ability to manually add the author and repository to the config file would help to keep stuff updated.

The best would be integration with Thunderstore as there are plenty of people that don't do proper releases in Github or don't have a repository at all, but I don't know if Thunderstore has an API that could be used.
It's also slow as balls most of the time :P

**Comment by ToyDragon** [comment]
I really want to encourage the community to use github for releases so we can see code changes and review them as a community. The core feature of enabling/disabling works without any effort from mod authors which I think is good enough for now. I'll still probably end up doing what you suggest and start checking thunderstore for updates too, but for now I'm submitting pull requests to mods I use to add UI and github info.

**Comment by ToyDragon** [comment]
I added version checking with Thunderstore earlier in the week. Thanks for the suggestion.
